name: CI

on:
  schedule:
   - cron: '0 1 * * *'
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: sandboxie-plus/Sandboxie

      - name: Patch source
        run: |
          "C:\Program Files\Git\usr\bin\patch.exe" -p1 -i .github/0001-Disable-cert-verification.patch

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Sandboxie x86
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=Win32 -maxcpucount:8

      - name: Build Sandboxie x64
        run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8

      - name: Install Qt 64 bit
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.*'
          arch: 'win64_msvc2019_64'
          cache: true

      - name: Installing Jom
        run: SandboxiePlus\install_jom.cmd

      - name: Build Sandboxie-Plus x64
        run: SandboxiePlus\qmake_plus.cmd x64

      - name: Build SbieShell x64
        run: msbuild /t:restore,build -p:RestorePackagesConfig=true SandboxiePlus\SbieShell\SbieShell.sln /p:Configuration="Release" /p:Platform=x64

      - name: Build Sandboxie-Tools x64
        run: msbuild /t:build SandboxieTools\SandboxieTools.sln /p:Configuration="Release" /p:Platform=x64 -maxcpucount:8

      - name: Merging Builds
        run: Installer\merge_builds.cmd

      - name: Collect installer assets
        run: Installer\get_assets.cmd

      - name: Upload Sandboxie x64
        uses: actions/upload-artifact@v3
        with:
          name: Sandboxie_x64
          if-no-files-found: error
          path: |
            Installer/SbiePlus_x64/*

      - name: Upload Sandboxie x86
        uses: actions/upload-artifact@v3
        with:
          name: Sandboxie_x86
          if-no-files-found: error
          path: |
            Installer/SbiePlus_x86/*

      - name: Upload SbieDrv.sys
        uses: actions/upload-artifact@v3
        with:
          name: SbieDrv.sys
          if-no-files-found: error
          path: |
            Installer/SbiePlus_x64/SbieDrv.sys
